version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env.docker
    depends_on:
      - redis
  
  redis:
    image: 'redis:latest'
    command: redis-server --bind '0.0.0.0'
    ports:
      - '6379:6379'